function[a,mur,sigmar]=Vasicek(alpha,beta,MSE,P,k,rt)
%ノAR(1)┮眔ぇ把计把计癬﹍秆Vasicek家┮惠把计alpha,beta,RMSEAR(1)︳璸把计,P琌ち澄计,k琌data丁羆,rt琌瞯妓セ
L=1;%pdf癬﹍
dt=1/12;%瞯–る跑笆
%ㄌ沮AR(1)戈癟崩旧把计癬﹍
RMSE=MSE^0.5;
sigmar=RMSE/(dt^0.5);
a=(1-beta)/dt;
mur=alpha/(a*dt);
%盢a,mu,sigma眖把计癬﹍0.0110暗单丁ち澄痻皚
%a猽X禸单丁筳ち澄,mu猽Y禸,sigma猽Z禸
apre1=linspace(0.01*a,10*a,P);
apre2=repmat(apre1',1,P);
aM=repmat(apre2,1,1,P);
murpre1=linspace(0.01*mur,10*mur,P);
murpre2=repmat(murpre1,P,1);
murM=repmat(murpre2,1,1,P);
sigmarpre1=linspace(0.01*sigmar,10*sigmar,P);
sigmarpre2=reshape(sigmarpre1,1,1,P);
sigmarpre3=repmat(sigmarpre2,1,P,1);
sigmarM=repmat(sigmarpre3,P,1,1);
%程阀ㄧ计
for i=1:k-1
    Z=((rt(i+1,1)-rt(i,1))-(aM.*(murM-rt(i,1)).*dt))./(2.*((sigmarM.^2).*dt));
    pdf=1./((2.*pi.*(sigmarM.^2).*dt).^0.5).*exp(-(Z.^2)/2);
    if i>1
        L=L.*pdf;
    else
        L=pdf;
    end
end
%―程阀ㄧ计程把计,ㄏノ把计︳璸
where=max(max(max(L)));
index=find(L==where);
[rowr,columnr,third]=ind2sub([P,P,P],index);
%块Vasicek家把计
a=aM(rowr,columnr,third);
mur=murM(rowr,columnr,third);
sigmar=sigmarM(rowr,columnr,third);